# Generated by Django 3.2.25 on 2024-12-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_msg', models.CharField(max_length=200)),
                ('alert_status', models.CharField(max_length=200)),
                ('alert_date', models.CharField(max_length=20)),
                ('alert_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='securityperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('id_proof', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureZone_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='survillancetask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survilance_task', models.CharField(max_length=200)),
                ('assign_date', models.CharField(max_length=20)),
                ('assing_day', models.CharField(max_length=50)),
                ('ALERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureZone_app.alert')),
                ('SECURITY_PERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureZone_app.securityperson')),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('report_date', models.CharField(max_length=20)),
                ('report_time', models.CharField(max_length=20)),
                ('SURVILANCE_TASK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureZone_app.survillancetask')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('complaint_date', models.CharField(max_length=50)),
                ('complaint_rply', models.CharField(max_length=200)),
                ('reply_date', models.CharField(max_length=20)),
                ('SECURITY_PERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureZone_app.securityperson')),
            ],
        ),
    ]
