# Generated by Django 3.2.25 on 2024-12-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureZone_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survillancetask',
            name='ALERT',
        ),
    ]
