# Generated by Django 3.2.25 on 2025-02-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecureZone_app', '0002_remove_survillancetask_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='sec_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('SECURITY_PERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureZone_app.securityperson')),
            ],
        ),
    ]
