# Generated by Django 3.2.25 on 2025-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureZone_app', '0003_sec_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_date',
            field=models.DateField(max_length=20),
        ),
    ]
